import type { Metadata } from "next";
import { getSiteEnv } from "@/lib/utils/env.public";
import { absoluteUrl } from "./site-url";

type BuildMetadataInput = {
  title: string;
  description: string;
  path: string;
  /** Use the title as-is instead of applying the "%s | U Design" template. */
  absoluteTitle?: boolean;
  type?: "website" | "article";
  noindex?: boolean;
  image?: { url: string; width?: number; height?: number; alt?: string };
  publishedTime?: string;
  modifiedTime?: string;
  authors?: string[];
};

export const SITE_NAME = "U Design";

/**
 * File-based `opengraph-image` routes apply only to their own segment: Next does not
 * inherit `app/opengraph-image.tsx` into nested routes. So every page states its image
 * here, and pages without a generated one fall back to the site image.
 */
export const SITE_OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "U Design: Digital Solutions That Help Businesses Grow",
} as const;

/** The image generated by the `opengraph-image` route colocated with `path`. */
export function entryOgImage(path: string, alt: string) {
  return { url: `${path}/opengraph-image`, width: 1200, height: 630, alt };
}

export function isIndexable(): boolean {
  return getSiteEnv() === "production";
}

/** Non-production deployments are never indexed; `noindex` pages stay followable. */
export function robotsFor(noindex = false): Pick<Metadata, "robots"> {
  if (!isIndexable()) return { robots: { index: false, follow: false } };
  if (noindex) return { robots: { index: false, follow: true } };
  return {};
}

/** One way to produce page metadata (plan AD-04). Every page passes its own title and description. */
export function buildMetadata({
  title,
  description,
  path,
  absoluteTitle = false,
  type = "website",
  noindex = false,
  image,
  publishedTime,
  modifiedTime,
  authors,
}: BuildMetadataInput): Metadata {
  const url = absoluteUrl(path);
  const socialTitle = absoluteTitle ? title : `${title} | ${SITE_NAME}`;
  const ogImage = image ?? SITE_OG_IMAGE;
  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title: socialTitle,
      description,
      url,
      siteName: SITE_NAME,
      locale: "en_US",
      type,
      images: [ogImage],
      ...(type === "article" ? { publishedTime, modifiedTime, authors } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: socialTitle,
      description,
      images: [ogImage.url],
    },
    ...robotsFor(noindex),
  };
}
