// Generates src/components/ui/icon-data.ts from lucide-react icon definitions.
// lucide-react v1 renders icons through a "use client" component, which turned
// every server-rendered icon into client JavaScript. Copying the SVG node data
// lets icons render as static server SVG (plan AD-12, zero client JS).
// Usage: node scripts/generate-icons.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";

const icons = {
  "arrow-down": "arrow-down",
  "arrow-right": "arrow-right",
  blocks: "blocks",
  boxes: "boxes",
  building: "building-2",
  calendar: "calendar",
  "chart-column": "chart-column",
  "chart-line": "chart-line",
  check: "check",
  "chevron-down": "chevron-down",
  "chevron-left": "chevron-left",
  "chevron-right": "chevron-right",
  "circle-alert": "circle-alert",
  "circle-check": "circle-check",
  "clipboard-list": "clipboard-list",
  clock: "clock",
  code: "code",
  compass: "compass",
  database: "database",
  download: "download",
  "external-link": "external-link",
  eye: "eye",
  factory: "factory",
  "file-spreadsheet": "file-spreadsheet",
  filter: "filter",
  gauge: "gauge",
  handshake: "handshake",
  "hard-hat": "hard-hat",
  "heart-pulse": "heart-pulse",
  layers: "layers",
  "layout-dashboard": "layout-dashboard",
  lightbulb: "lightbulb",
  link: "link",
  "list-checks": "list-checks",
  "log-out": "log-out",
  mail: "mail",
  "map-pin": "map-pin",
  megaphone: "megaphone",
  menu: "menu",
  "message-square": "message-square",
  monitor: "monitor",
  "more-horizontal": "more-horizontal",
  package: "package",
  "pen-line": "pen-line",
  phone: "phone",
  plane: "plane",
  puzzle: "puzzle",
  "refresh-cw": "refresh-cw",
  rocket: "rocket",
  route: "route",
  search: "search",
  share: "share-2",
  "shield-check": "shield-check",
  "shopping-bag": "shopping-bag",
  "sliders-horizontal": "sliders-horizontal",
  sprout: "sprout",
  target: "target",
  "trash-2": "trash-2",
  "trending-up": "trending-up",
  truck: "truck",
  users: "users",
  warehouse: "warehouse",
  workflow: "workflow",
  x: "x",
  zap: "zap",
};

const entries = [];
for (const [key, file] of Object.entries(icons)) {
  // Some icon files are aliases (e.g. building-2 → building-complex); follow them.
  let path = `node_modules/lucide-react/dist/esm/icons/${file}.mjs`;
  let source = readFileSync(path, "utf8");
  const alias = source.match(/export \{ default \} from '\.\/([a-z0-9-]+)\.mjs'/);
  if (alias) {
    path = `node_modules/lucide-react/dist/esm/icons/${alias[1]}.mjs`;
    source = readFileSync(path, "utf8");
  }
  const { __iconData } = await import(pathToFileURL(path).href);
  const nodes = __iconData.node.map(([tag, attrs]) => {
    const { key: _key, ...rest } = attrs;
    return [tag, rest];
  });
  entries.push(`  ${JSON.stringify(key)}: ${JSON.stringify(nodes)},`);
}

const out = `// Generated by scripts/generate-icons.mjs from lucide-react (ISC License,
// https://lucide.dev). Do not edit by hand; add icons to the script instead.

export type IconNode = [tag: string, attrs: Record<string, string | number>][];

export const iconData = {
${entries.join("\n")}
} satisfies Record<string, IconNode>;
`;
writeFileSync("src/components/ui/icon-data.ts", out);
process.stdout.write(`wrote ${entries.length} icons${String.fromCharCode(10)}`);
